In [1]:
#importing necessary libraries

import numpy as np
import gym
import random

In [2]:
# Defining an environment
env = gym.make("Taxi-v3")

In [3]:
# how the output will look like
env.render()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [4]:
# define the number of actions and state agent can choose from

action_size = env.action_space.n
state_size = env.observation_space.n

print("Action space :",action_size)
print("State size : ",state_size)

Action space : 6
State size :  500


In [5]:
# Defining a Q_table

q_table = np.zeros((state_size, action_size))
print(q_table)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [6]:
# defining Hyper-parameters

total_epochs = 2000
total_test_epochs = 100
max_steps = 100
lr = 0.81
gamma = 0.96


# Defining exploration-exploitation parameters

epsilon = 0.9
max_epsilon = 1.0
min_epsilon = 0.01
decay_rate = 0.1

In [7]:
# iterate for total number of episodes

for epochs in range(total_epochs):
    
    #reset the state
    state = env.reset()
    done = False
    
    #iterate for max step
    for step in range(max_steps):
        
        # Choose a random exploration-exploitation-tradeoff
        exp_exp_tradeoff = random.uniform(0,1)
        
        # if exploration-exploitation-tradeoff is greater then epsilon the exploit and choose the best action
        # from the Q-Table
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(q_table[state,:])
            
        # if exploration-exploitation-tradeoff is less then epsilon then choose a random action
        else:
            action = env.action_space.sample()
            
        # acquire the reward and next state
        new_state, reward, done, info = env.step(action)
        
        # update the Q_table based on formula
        q_table[state, action] = q_table[state, action] + lr * (reward + gamma * 
                                    np.max(q_table[new_state, :]) - q_table[state, action])
        
        # set state to next state
        state = new_state
        
        if done: break
    
    # reduce the epsilon to reduce the exploitaion 
    epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate*epochs)

In [8]:
# reset the env and declare vars
env.reset()
reward_list = []
total_reward = 0

# iterate for total test epochs
for epochs in range(total_test_epochs):
    
    # set state by reseting the environment
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    print('=========================')
    print('EPISODE: ', epochs)
    
    #iterate for every step
    for step in range(max_steps):
        
        env.render()
        
        # choose the action greedily
        action = np.argmax(q_table[state,:])
        
        state, reward, done, info = env.step(action)
        
        # add the reward to total_reward for each iteration
        total_reward += reward
        
        if done:
            reward_list.append(total_reward)
            print('Score: ', total_reward)
            break
            
    # set state to next state
    state = new_state

env.close()
print('Score Over Time: {}'.format(sum(reward_list)/total_test_epochs))

EPISODE:  0
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
+---------+
|R: | : :G|
|_: | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
|_: : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| :_: : : |
| | : | : |


  (East)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : |_: |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| : : :_: |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| : :_: : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : | : : |
| :_: : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| :_| : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
|_: | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : 

EPISODE:  96
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
+---------+
|R: | : :G|
| : | : :_|
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | :_: |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : | : : |
| : : :_: |
| | : | : |
